extends:
  - airbnb-base
  - prettier
plugins:
  - import
  - no-unsanitized
env:
  node: true
  browser: true
  es6: true
  mocha: true
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  no-unsanitized/method: error
  no-unsanitized/property: error
overrides:
  - { files: ['*.spec.js'],
      rules: {
        no-unsanitized/method: off,
        no-unsanitized/property: off
        }
      }
  - files: ['uswds-init.js']
    rules:
      # Flagged addEventListener is not "used by mistake", intending global
      # See: https://www.npmjs.com/package/confusing-browser-globals
      no-restricted-globals: off
