const { src, dest } = require("gulp");
const rename = require("gulp-rename");
const dutil = require("./utils/doc-util");

const usaIcons = [
  "./node_modules/@material-design-icons/svg/outlined/accessibility_new.svg",
  "./node_modules/@material-design-icons/svg/outlined/accessible_forward.svg",
  "./node_modules/@material-design-icons/svg/outlined/account_balance.svg",
  "./node_modules/@material-design-icons/svg/outlined/account_box.svg",
  "./node_modules/@material-design-icons/svg/outlined/account_circle.svg",
  "./node_modules/@material-design-icons/svg/outlined/add_circle_outline.svg",
  "./node_modules/@material-design-icons/svg/outlined/add_circle.svg",
  "./node_modules/@material-design-icons/svg/outlined/add.svg",
  "./node_modules/@material-design-icons/svg/outlined/alarm.svg",
  "./node_modules/@material-design-icons/svg/outlined/alternate_email.svg",
  "./node_modules/@material-design-icons/svg/outlined/announcement.svg",
  "./node_modules/@material-design-icons/svg/outlined/api.svg",
  "./node_modules/@material-design-icons/svg/outlined/arrow_back.svg",
  "./node_modules/@material-design-icons/svg/outlined/arrow_downward.svg",
  "./node_modules/@material-design-icons/svg/outlined/arrow_drop_down.svg",
  "./node_modules/@material-design-icons/svg/outlined/arrow_drop_up.svg",
  "./node_modules/@material-design-icons/svg/outlined/arrow_forward.svg",
  "./node_modules/@material-design-icons/svg/outlined/arrow_upward.svg",
  "./node_modules/@material-design-icons/svg/outlined/assessment.svg",
  "./node_modules/@material-design-icons/svg/outlined/attach_file.svg",
  "./node_modules/@material-design-icons/svg/outlined/attach_money.svg",
  "./node_modules/@material-design-icons/svg/outlined/autorenew.svg",
  "./node_modules/@material-design-icons/svg/outlined/backpack.svg",
  "./node_modules/@material-design-icons/svg/outlined/bathtub.svg",
  "./node_modules/@material-design-icons/svg/outlined/bookmark.svg",
  "./node_modules/@material-design-icons/svg/outlined/bug_report.svg",
  "./node_modules/@material-design-icons/svg/outlined/build.svg",
  "./node_modules/@material-design-icons/svg/outlined/calendar_today.svg",
  "./node_modules/@material-design-icons/svg/outlined/campaign.svg",
  "./node_modules/@material-design-icons/svg/outlined/cancel.svg",
  "./node_modules/@material-design-icons/svg/outlined/chat.svg",
  "./node_modules/@material-design-icons/svg/outlined/check_box_outline_blank.svg",
  "./node_modules/@material-design-icons/svg/outlined/check_circle_outline.svg",
  "./node_modules/@material-design-icons/svg/outlined/check_circle.svg",
  "./node_modules/@material-design-icons/svg/outlined/check.svg",
  "./node_modules/@material-design-icons/svg/outlined/checkroom.svg",
  "./node_modules/@material-design-icons/svg/outlined/clean_hands.svg",
  "./node_modules/@material-design-icons/svg/outlined/close.svg",
  "./node_modules/@material-design-icons/svg/outlined/closed_caption.svg",
  "./node_modules/@material-design-icons/svg/outlined/cloud.svg",
  "./node_modules/@material-design-icons/svg/outlined/code.svg",
  "./node_modules/@material-design-icons/svg/outlined/comment.svg",
  "./node_modules/@material-design-icons/svg/outlined/connect_without_contact.svg",
  "./node_modules/@material-design-icons/svg/outlined/construction.svg",
  "./node_modules/@material-design-icons/svg/outlined/contact_page.svg",
  "./node_modules/@material-design-icons/svg/outlined/content_copy.svg",
  "./node_modules/@material-design-icons/svg/outlined/coronavirus.svg",
  "./node_modules/@material-design-icons/svg/outlined/credit_card.svg",
  "./node_modules/@material-design-icons/svg/outlined/deck.svg",
  "./node_modules/@material-design-icons/svg/outlined/delete.svg",
  "./node_modules/@material-design-icons/svg/outlined/device_thermostat.svg",
  "./node_modules/@material-design-icons/svg/outlined/directions_bike.svg",
  "./node_modules/@material-design-icons/svg/outlined/directions_bus.svg",
  "./node_modules/@material-design-icons/svg/outlined/directions_car.svg",
  "./node_modules/@material-design-icons/svg/outlined/directions_walk.svg",
  "./node_modules/@material-design-icons/svg/outlined/directions.svg",
  "./node_modules/@material-design-icons/svg/outlined/do_not_disturb.svg",
  "./node_modules/@material-design-icons/svg/outlined/do_not_touch.svg",
  "./node_modules/@material-design-icons/svg/outlined/drag_handle.svg",
  "./node_modules/@material-design-icons/svg/outlined/edit.svg",
  "./node_modules/@material-design-icons/svg/outlined/electrical_services.svg",
  "./node_modules/@material-design-icons/svg/outlined/emoji_events.svg",
  "./node_modules/@material-design-icons/svg/outlined/error_outline.svg",
  "./node_modules/@material-design-icons/svg/outlined/error.svg",
  "./node_modules/@material-design-icons/svg/outlined/event.svg",
  "./node_modules/@material-design-icons/svg/outlined/expand_less.svg",
  "./node_modules/@material-design-icons/svg/outlined/expand_more.svg",
  "./node_modules/@material-design-icons/svg/outlined/fast_forward.svg",
  "./node_modules/@material-design-icons/svg/outlined/fast_rewind.svg",
  "./node_modules/@material-design-icons/svg/outlined/favorite_border.svg",
  "./node_modules/@material-design-icons/svg/outlined/favorite.svg",
  "./node_modules/@material-design-icons/svg/outlined/file_download.svg",
  "./node_modules/@material-design-icons/svg/outlined/file_present.svg",
  "./node_modules/@material-design-icons/svg/outlined/file_upload.svg",
  "./node_modules/@material-design-icons/svg/outlined/filter_alt.svg",
  "./node_modules/@material-design-icons/svg/outlined/filter_list.svg",
  "./node_modules/@material-design-icons/svg/outlined/fingerprint.svg",
  "./node_modules/@material-design-icons/svg/outlined/first_page.svg",
  "./node_modules/@material-design-icons/svg/outlined/flag.svg",
  "./node_modules/@material-design-icons/svg/outlined/flight.svg",
  "./node_modules/@material-design-icons/svg/outlined/folder_open.svg",
  "./node_modules/@material-design-icons/svg/outlined/folder.svg",
  "./node_modules/@material-design-icons/svg/outlined/format_quote.svg",
  "./node_modules/@material-design-icons/svg/outlined/format_size.svg",
  "./node_modules/@material-design-icons/svg/outlined/forum.svg",
  "./node_modules/@material-design-icons/svg/outlined/grid_view.svg",
  "./node_modules/@material-design-icons/svg/outlined/group_add.svg",
  "./node_modules/@material-design-icons/svg/outlined/groups.svg",
  "./node_modules/@material-design-icons/svg/outlined/hearing.svg",
  "./node_modules/@material-design-icons/svg/outlined/help_outline.svg",
  "./node_modules/@material-design-icons/svg/outlined/help.svg",
  "./node_modules/@material-design-icons/svg/outlined/highlight_off.svg",
  "./node_modules/@material-design-icons/svg/outlined/history.svg",
  "./node_modules/@material-design-icons/svg/outlined/home.svg",
  "./node_modules/@material-design-icons/svg/outlined/hotel.svg",
  "./node_modules/@material-design-icons/svg/outlined/hourglass_empty.svg",
  "./node_modules/@material-design-icons/svg/outlined/image.svg",
  "./node_modules/@material-design-icons/svg/outlined/info.svg",
  "./node_modules/@material-design-icons/svg/outlined/insights.svg",
  "./node_modules/@material-design-icons/svg/outlined/keyboard.svg",
  "./node_modules/@material-design-icons/svg/outlined/label.svg",
  "./node_modules/@material-design-icons/svg/outlined/language.svg",
  "./node_modules/@material-design-icons/svg/outlined/last_page.svg",
  "./node_modules/@material-design-icons/svg/outlined/launch.svg",
  "./node_modules/@material-design-icons/svg/outlined/lightbulb.svg",
  "./node_modules/@material-design-icons/svg/outlined/link_off.svg",
  "./node_modules/@material-design-icons/svg/outlined/link.svg",
  "./node_modules/@material-design-icons/svg/outlined/list.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_cafe.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_fire_department.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_gas_station.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_grocery_store.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_hospital.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_laundry_service.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_library.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_offer.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_parking.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_pharmacy.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_police.svg",
  "./node_modules/@material-design-icons/svg/outlined/local_taxi.svg",
  "./node_modules/@material-design-icons/svg/outlined/location_city.svg",
  "./node_modules/@material-design-icons/svg/outlined/location_on.svg",
  "./node_modules/@material-design-icons/svg/outlined/lock_open.svg",
  "./node_modules/@material-design-icons/svg/outlined/lock.svg",
  "./node_modules/@material-design-icons/svg/outlined/login.svg",
  "./node_modules/@material-design-icons/svg/outlined/logout.svg",
  "./node_modules/@material-design-icons/svg/outlined/loop.svg",
  "./node_modules/@material-design-icons/svg/outlined/mail_outline.svg",
  "./node_modules/@material-design-icons/svg/outlined/mail.svg",
  "./node_modules/@material-design-icons/svg/outlined/map.svg",
  "./node_modules/@material-design-icons/svg/outlined/masks.svg",
  "./node_modules/@material-design-icons/svg/outlined/medical_services.svg",
  "./node_modules/@material-design-icons/svg/outlined/menu.svg",
  "./node_modules/@material-design-icons/svg/outlined/military_tech.svg",
  "./node_modules/@material-design-icons/svg/outlined/more_horiz.svg",
  "./node_modules/@material-design-icons/svg/outlined/more_vert.svg",
  "./node_modules/@material-design-icons/svg/outlined/my_location.svg",
  "./node_modules/@material-design-icons/svg/outlined/navigate_before.svg",
  "./node_modules/@material-design-icons/svg/outlined/navigate_next.svg",
  "./node_modules/@material-design-icons/svg/outlined/near_me.svg",
  "./node_modules/@material-design-icons/svg/outlined/notifications_active.svg",
  "./node_modules/@material-design-icons/svg/outlined/notifications_none.svg",
  "./node_modules/@material-design-icons/svg/outlined/notifications_off.svg",
  "./node_modules/@material-design-icons/svg/outlined/notifications.svg",
  "./node_modules/@material-design-icons/svg/outlined/park.svg",
  "./node_modules/@material-design-icons/svg/outlined/people.svg",
  "./node_modules/@material-design-icons/svg/outlined/person.svg",
  "./node_modules/@material-design-icons/svg/outlined/pets.svg",
  "./node_modules/@material-design-icons/svg/outlined/phone.svg",
  "./node_modules/@material-design-icons/svg/outlined/photo_camera.svg",
  "./node_modules/@material-design-icons/svg/outlined/print.svg",
  "./node_modules/@material-design-icons/svg/outlined/priority_high.svg",
  "./node_modules/@material-design-icons/svg/outlined/public.svg",
  "./node_modules/@material-design-icons/svg/outlined/push_pin.svg",
  "./node_modules/@material-design-icons/svg/outlined/radio_button_unchecked.svg",
  "./node_modules/@material-design-icons/svg/outlined/reduce_capacity.svg",
  "./node_modules/@material-design-icons/svg/outlined/remove.svg",
  "./node_modules/@material-design-icons/svg/outlined/report.svg",
  "./node_modules/@material-design-icons/svg/outlined/restaurant.svg",
  "./node_modules/@material-design-icons/svg/outlined/rss_feed.svg",
  "./node_modules/@material-design-icons/svg/outlined/safety_divider.svg",
  "./node_modules/@material-design-icons/svg/outlined/sanitizer.svg",
  "./node_modules/@material-design-icons/svg/outlined/save_alt.svg",
  "./node_modules/@material-design-icons/svg/outlined/schedule.svg",
  "./node_modules/@material-design-icons/svg/outlined/school.svg",
  "./node_modules/@material-design-icons/svg/outlined/science.svg",
  "./node_modules/@material-design-icons/svg/outlined/search.svg",
  "./node_modules/@material-design-icons/svg/outlined/security.svg",
  "./node_modules/@material-design-icons/svg/outlined/send.svg",
  "./node_modules/@material-design-icons/svg/outlined/sentiment_dissatisfied.svg",
  "./node_modules/@material-design-icons/svg/outlined/sentiment_neutral.svg",
  "./node_modules/@material-design-icons/svg/outlined/sentiment_satisfied_alt.svg",
  "./node_modules/@material-design-icons/svg/outlined/sentiment_satisfied.svg",
  "./node_modules/@material-design-icons/svg/outlined/sentiment_very_dissatisfied.svg",
  "./node_modules/@material-design-icons/svg/outlined/settings.svg",
  "./node_modules/@material-design-icons/svg/outlined/share.svg",
  "./node_modules/@material-design-icons/svg/outlined/shield.svg",
  "./node_modules/@material-design-icons/svg/outlined/shopping_basket.svg",
  "./node_modules/@material-design-icons/svg/outlined/soap.svg",
  "./node_modules/@material-design-icons/svg/outlined/social_distance.svg",
  "./node_modules/@material-design-icons/svg/outlined/spellcheck.svg",
  "./node_modules/@material-design-icons/svg/outlined/star_half.svg",
  "./node_modules/@material-design-icons/svg/outlined/star_outline.svg",
  "./node_modules/@material-design-icons/svg/outlined/star.svg",
  "./node_modules/@material-design-icons/svg/outlined/store.svg",
  "./node_modules/@material-design-icons/svg/outlined/support_agent.svg",
  "./node_modules/@material-design-icons/svg/outlined/support.svg",
  "./node_modules/@material-design-icons/svg/outlined/text_fields.svg",
  "./node_modules/@material-design-icons/svg/outlined/thumb_down_alt.svg",
  "./node_modules/@material-design-icons/svg/outlined/thumb_up_alt.svg",
  "./node_modules/@material-design-icons/svg/outlined/timer.svg",
  "./node_modules/@material-design-icons/svg/outlined/toggle_off.svg",
  "./node_modules/@material-design-icons/svg/outlined/toggle_on.svg",
  "./node_modules/@material-design-icons/svg/outlined/topic.svg",
  "./node_modules/@material-design-icons/svg/outlined/translate.svg",
  "./node_modules/@material-design-icons/svg/outlined/trending_down.svg",
  "./node_modules/@material-design-icons/svg/outlined/trending_up.svg",
  "./node_modules/@material-design-icons/svg/outlined/undo.svg",
  "./node_modules/@material-design-icons/svg/outlined/unfold_less.svg",
  "./node_modules/@material-design-icons/svg/outlined/unfold_more.svg",
  "./node_modules/@material-design-icons/svg/outlined/update.svg",
  "./node_modules/@material-design-icons/svg/outlined/upload_file.svg",
  "./node_modules/@material-design-icons/svg/outlined/verified_user.svg",
  "./node_modules/@material-design-icons/svg/outlined/verified.svg",
  "./node_modules/@material-design-icons/svg/outlined/visibility_off.svg",
  "./node_modules/@material-design-icons/svg/outlined/visibility.svg",
  "./node_modules/@material-design-icons/svg/outlined/volume_off.svg",
  "./node_modules/@material-design-icons/svg/outlined/warning.svg",
  "./node_modules/@material-design-icons/svg/outlined/wash.svg",
  "./node_modules/@material-design-icons/svg/outlined/wifi.svg",
  "./node_modules/@material-design-icons/svg/outlined/work.svg",
  "./node_modules/@material-design-icons/svg/outlined/zoom_in.svg",
  "./node_modules/@material-design-icons/svg/outlined/zoom_out_map.svg",
  "./node_modules/@material-design-icons/svg/outlined/zoom_out.svg",
  "./packages/usa-icon/src/img/material-icons-deprecated/eco.svg",
  "./packages/usa-icon/src/img/material-icons-deprecated/facebook.svg",
  "./packages/usa-icon/src/img/material-icons-deprecated/info_outline.svg",
  "./packages/usa-icon/src/img/material-icons-deprecated/lightbulb_outline.svg",
  "./packages/usa-icon/src/img/material-icons-deprecated/lock_outline.svg",
  "./packages/usa-icon/src/img/uswds-icons/bedding.svg",
  "./packages/usa-icon/src/img/uswds-icons/camping.svg",
  "./packages/usa-icon/src/img/uswds-icons/chevron_left.svg",
  "./packages/usa-icon/src/img/uswds-icons/chevron_right.svg",
  "./packages/usa-icon/src/img/uswds-icons/clothes.svg",
  "./packages/usa-icon/src/img/uswds-icons/construction_worker.svg",
  "./packages/usa-icon/src/img/uswds-icons/flickr.svg",
  "./packages/usa-icon/src/img/uswds-icons/flooding.svg",
  "./packages/usa-icon/src/img/uswds-icons/github.svg",
  "./packages/usa-icon/src/img/uswds-icons/hospital.svg",
  "./packages/usa-icon/src/img/uswds-icons/hurricane.svg",
  "./packages/usa-icon/src/img/uswds-icons/identification.svg",
  "./packages/usa-icon/src/img/uswds-icons/instagram.svg",
  "./packages/usa-icon/src/img/uswds-icons/navigate_far_before.svg",
  "./packages/usa-icon/src/img/uswds-icons/navigate_far_next.svg",
  "./packages/usa-icon/src/img/uswds-icons/rain.svg",
  "./packages/usa-icon/src/img/uswds-icons/severe_weather.svg",
  "./packages/usa-icon/src/img/uswds-icons/snow.svg",
  "./packages/usa-icon/src/img/uswds-icons/sort_arrow.svg",
  "./packages/usa-icon/src/img/uswds-icons/tornado.svg",
  "./packages/usa-icon/src/img/uswds-icons/twitter.svg",
  "./packages/usa-icon/src/img/uswds-icons/youtube.svg",
];

module.exports = {
  // Copy theme settings files to /dist directory
  copyTheme() {
    dutil.logMessage(
      "copyTheme",
      "Copying theme settings files to /dist/theme"
    );
    return src("packages/uswds-core/src/theme/*.scss").pipe(dest("dist/theme"));
  },

  // Copy Sass stylesheets to /dist directory
  // TODO: Do we want to copy to the scss any more?
  copySass() {
    dutil.logMessage("copySass", "Copying Sass stylesheets to /dist/scss");
    return src("src/**/**/*.scss").pipe(dest("dist/scss"));
  },

  // Copy material icons to /dist/img/material-icons
  copyIconSrc() {
    dutil.logMessage("copyIconSrc", "Copying Material icons to dist/img/material-icons");
    return src(["node_modules/@material-design-icons/svg/outlined/*"])
      .pipe(dest("dist/img/material-icons"));
  },

  // Copy default icons to /dist/img/usa-icons
  copyIconSet() {
    dutil.logMessage("copyIconSelects", "Copying default icon set to dist/img/usa-icons");
    return src(usaIcons)
      .pipe(dest("dist/img/usa-icons"))
  },

  // Copy images to /dist directory
  copyImages() {
    dutil.logMessage("copyImages", "Copying images to /dist/img");
    return src(["packages/**/src/img/**/*{png,jpg,gif,webp,svg,ico}"])
      .pipe(
        // use only the part of the path specific to the package img dir
        rename((path) => {
          path.dirname = path.dirname.replace(/[a-z-]+?\/src\/img/i, "");
          return path;
        })
      )
      .pipe(dest("dist/img"));
  },


  // Copy fonts to /dist directory
  copyFonts() {
    dutil.logMessage("copyFonts", "Copying fonts to /dist/fonts");
    return src("packages/uswds-core/src/assets/fonts/**/*").pipe(
      dest("dist/fonts")
    );
  },
};
