name: CI Documentation Checks

on:
  schedule:
    # This runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin v6.0.2
      - uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # pin v1.1.2
        with:
          use-quiet-mode: "yes"
          config-file: .github/workflows/markdownlink-config.json
