name: NodeJS with Webpack

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: MacOS

    strategy:
      matrix:
        node-version: [23.x, 24.x, 25.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm update npm
        npm install  
        npm run webpack
        
